# Generated by Django 4.1 on 2023-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_rename_comment_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="date", field=models.DateField(auto_now=True),
        ),
    ]
