# Generated by Django 4.1 on 2023-01-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="date",),
    ]
