# Generated by Django 4.1 on 2023-01-13 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_post_date"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={"ordering": ["-date"]},),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
